# Generated by Django 4.2.16 on 2025-12-06 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_auto_20211109_1456'),
        ('geography', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='busstop',
            name='unique_stop_order_per_shift',
        ),
        migrations.AlterField(
            model_name='busshift',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.bus'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('planned', 'Prévu'), ('done', 'Terminé')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.place'),
        ),
    ]
