# Generated by Django 4.2.16 on 2025-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_remove_busstop_unique_stop_order_per_shift_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('prévu', 'Prévu'), ('terminé', 'Terminé')], default='brouillon', max_length=20),
        ),
    ]
