# Generated by Django 4.2.16 on 2025-12-06 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_alter_busshift_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='shift',
            new_name='bus_shift',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='busstop',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
