# Generated by Django 4.2.16 on 2025-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_rename_shift_busstop_bus_shift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='bus_shift',
            new_name='shift',
        ),
        migrations.AddField(
            model_name='busshift',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busshift',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busshift',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('planned', 'Prévu'), ('done', 'Terminé')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
