# Generated by Django 4.2.16 on 2025-12-07 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
        ('fleet', '0002_auto_20211109_1456'),
        ('transport', '0005_rename_bus_shift_busstop_shift_busshift_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busshift',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='fleet.bus'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='fleet.driver'),
        ),
        migrations.AlterField(
            model_name='busshift',
            name='status',
            field=models.CharField(choices=[('Brouillon', 'Brouillon'), ('Prévu', 'Prévu'), ('Terminé', 'Terminé')], default='Brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geography.place'),
        ),
    ]
