# Generated by Django 4.2.16 on 2025-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_busshift_bus_alter_busshift_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='busshift',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='busshift',
            name='status',
            field=models.CharField(default='Brouillon', max_length=20),
        ),
    ]
