# Generated by Django 4.2.16 on 2025-12-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_remove_busshift_created_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='busstop',
            constraint=models.UniqueConstraint(fields=('shift', 'order'), name='unique_stop_order_per_shift'),
        ),
    ]
