# Generated by Django 4.2.16 on 2025-12-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_busstop_unique_stop_order_per_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busshift',
            name='status',
        ),
    ]
